--- !ruby/object:FreeBASE::PluginConfiguration
name: redcar
description: Redcar standard libraries
version: 1.0
author: Daniel Lucraft
autoload: false
require_path: redcar/redcar.rb
startup_module: Redcar::
load_dependencies: 
  core: "*"
  application: "*"
  application_swt: "*"
start_dependencies: 
  core: "*"
  application: "*"
  application_swt: "*"
