--- !ditz.rubyforge.org,2008-03-06/project 
name: redcar
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: redcar
- !ditz.rubyforge.org,2008-03-06/component 
  name: release-packaging
- !ditz.rubyforge.org,2008-03-06/component 
  name: core
- !ditz.rubyforge.org,2008-03-06/component 
  name: project-plugin
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.1"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2008-10-14 20:38:47.470719 Z
    - Daniel Lucraft <dan@fluentradical.com>
    - created
    - First public release.
