--- !ruby/object:FreeBASE::SubsystemConfiguration 
name: core
version: 1.0
plugins: 
  - !ruby/object:FreeBASE::PluginConfiguration 
    name:            core\gui-main
    version:         1.0
    autoload:        true
    require_path:    core/gui_main
    startup_module:  Redcar::Plugins::GuiMain
    properties_path: gui-main.yaml


