--- !ruby/object:FreeBASE::SubsystemConfiguration 
name: core
version: 1.0
plugins: 
  - !ruby/object:FreeBASE::PluginConfiguration 
    name:            core-edit_tab
    autoload:        true
    require_path:    core/edit_tab
    startup_module:  Redcar::EditTab
    load_dependencies:
        core-tab: "*"
        core-document: "*"
        core-edit_view: "*"

  - !ruby/object:FreeBASE::PluginConfiguration 
    name:            core-document
    autoload:        true
    require_path:    core/document
    startup_module:  Redcar::Document
    load_dependencies:
        core-edit_view: "*"
        core-plugin:    "*"
        core-window:    "*"
    tests:
      - path: core/tests/document_test.rb
        testcase: Redcar::Tests::DocumentTest

  - !ruby/object:FreeBASE::PluginConfiguration 
    name:            core-edit_view
    autoload:        true
    require_path:    core/edit_view
    startup_module:  Redcar::EditView
    load_dependencies:
        core-plugin: "*"

  - !ruby/object:FreeBASE::PluginConfiguration 
    name:            core-standard_menus
    autoload:        true
    require_path:    core/standard_menus
    startup_module:  Redcar::StandardMenus
    load_dependencies:
        core-app: "*"
        core-tab: "*"
        core-window: "*"

  - !ruby/object:FreeBASE::PluginConfiguration 
    name:            core-gui
    autoload:        true
    require_path:    core/gui
    startup_module:  Redcar::Gui
    start_dependencies:
        core-app: "*"

  - !ruby/object:FreeBASE::PluginConfiguration 
    name:            core-app
    autoload:        true
    require_path:    core/app
    startup_module:  Redcar::App
    start_dependencies:
        core-window: "*"

  - !ruby/object:FreeBASE::PluginConfiguration 
    name:            core-window
    autoload:        true
    require_path:    core/window
    startup_module:  Redcar::Window
    load_dependencies:
        core-sensitive: "*"
    start_dependencies:
        core-keymap: "*"
        core-pane: "*"
        core-menu: "*"
        core-speedbar: "*"
    tests:
      - path: core/tests/window_test.rb
        testcase: Redcar::PluginTests::WindowTest

  - !ruby/object:FreeBASE::PluginConfiguration 
    name:            core-pane
    autoload:        true
    require_path:    core/pane
    startup_module:  Redcar::Pane
    start_dependencies:
        core-tab: "*"
    tests:
      - path: core/tests/pane_test.rb
        testcase: Redcar::PluginTests::PaneTest

  - !ruby/object:FreeBASE::PluginConfiguration 
    name:            core-tab
    autoload:        true
    require_path:    core/tab
    startup_module:  Redcar::Tab
    load_dependencies:
        core-plugin: "*"
    tests:
      - path: core/tests/tab_test.rb
        testcase: Redcar::PluginTests::TabTest

  - !ruby/object:FreeBASE::PluginConfiguration 
    name:            core-speedbar
    autoload:        true
    require_path:    core/speedbar
    startup_module:  Redcar::Speedbar
    load_dependencies:
        core-plugin: "*"
    tests:
      - path: core/tests/speedbar_test.rb
        testcase: Redcar::PluginTests::SpeedbarTest

  - !ruby/object:FreeBASE::PluginConfiguration 
    name:            core-plugin
    autoload:        true
    require_path:    core/plugin
    startup_module:  Redcar::Plugin
    load_dependencies:
        core-menu: "*"
        core-command: "*"
        core-preference: "*"

  - !ruby/object:FreeBASE::PluginConfiguration 
    name:            core-preference
    autoload:        true
    require_path:    core/preference
    startup_module:  Redcar::Preference
    load_dependencies:
        core-app: "*"

  - !ruby/object:FreeBASE::PluginConfiguration 
    name:            core-menu
    autoload:        true
    require_path:    core/menu
    startup_module:  Redcar::Menu
    load_dependencies:
        core-command: "*"

  - !ruby/object:FreeBASE::PluginConfiguration 
    name:            core-command
    autoload:        true
    require_path:    core/command
    startup_module:  Redcar::Command
    load_dependencies:
        core-keymap: "*"
        core-sensitive: "*"
    tests:
      - path: core/tests/command_test.rb
        testcase: Redcar::Tests::CommandTest
      - path: core/tests/command_history_test.rb
        testcase: Redcar::Tests::CommandHistoryTest

  - !ruby/object:FreeBASE::PluginConfiguration 
    name:            core-keymap
    autoload:        true
    require_path:    core/keymap
    startup_module:  Redcar::Keymap
    tests:
      - path: core/tests/keymap_test.rb
        testcase: Redcar::Tests::KeymapTest

  - !ruby/object:FreeBASE::PluginConfiguration 
    name:            core-sensitive
    autoload:        true
    require_path:    core/sensitive
    startup_module:  Redcar::Sensitive
    load_dependencies:
        core-hook: "*"
    tests:
      - path: core/tests/sensitive_test.rb
        testcase: Redcar::Tests::SensitiveTest

  - !ruby/object:FreeBASE::PluginConfiguration 
    name:            core-hook
    autoload:        true
    require_path:    core/hook
    startup_module:  Redcar::Hook
    tests:
      - path: core/tests/hook_test.rb
        testcase: Redcar::PluginTests::HookTest
