--- !ruby/object:FreeBASE::PluginConfiguration 
name: plugin-manager
description: Adds the Plugin Manager option to the Tools menu.
author: Daniel Lucraft
version: 1.0
autoload: false #true
require_path: plugin_manager/plugin_manager.rb
startup_module: Com::RedcarIDE::PluginManager
tests:
  - path: plugin_manager/test.rb
    testcase: Com::RedcarIDE::PluginManager::Test
load_dependencies: 
  core: "*"
start_dependencies: 
  core: "*"