--- !ruby/object:FreeBASE::PluginConfiguration 
name: scripting
description: Tools for scripting Redcar.
author: Daniel Lucraft
version: 1.0
autoload: (true)
require_path: scripting/scripting.rb
startup_module: Redcar::Plugins::Scripting
tests:
  - path: scripting/test.rb
    testcase: Redcar::PluginTests::ScriptingTest
load_dependencies: 
  core: "*"
start_dependencies: 
  core: "*"